[profile.release]
opt-level = 3
lto = true
codegen-units = 1

[package]
name = "userv"
description = "Program design to retrieve and compute machine data"
edition = "2024"
license = "GPL3.0"
version = "0.1.5"

[dependencies]
log = "0.4"
log4rs = "1.3"
clap = { version = "4.0", features = ["derive"] }
openssl = { version = "0.10", features = ["vendored"] }

board = { path = "./src/probes/board" }
cpu = { path = "./src/probes/cpu" }
gpu = { path = "./src/probes/gpu" }
memory = { path = "./src/probes/memory" }
network = { path = "./src/probes/network" }
storage = { path = "./src/probes/storage" }
system = { path = "./src/probes/system" }

core = { path = "./src/core" }
gui_web = { path = "./src/gui/web" }

[workspace]
resolver = "3"
members = [
    "./src/probes/board",
    "./src/probes/cpu",
    "./src/probes/gpu",
    "./src/probes/memory",
    "./src/probes/network",
    "./src/probes/storage",
    "./src/probes/system",
    "./src/core",
    "./src/gui/web"
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
core = { path = "./src/core" }

actix = "0.13"
actix-files = "0.6"
actix-web = "4"
actix-web-actors = "4"
chrono = "0.4"
env_logger = "0.11.8"
dmidecode = "1.0"
libc = "0.2"
log = "0.4"
nvml-wrapper = "0.11"
once_cell = "1.21"
serde = "1.0"
sysinfo = "0.37"
tempfile = "3.3.0"
regex = "1.11"
rusqlite = "0.37"
