[profile.release]
opt-level = 1
lto = true
codegen-units = 1

[package]
name = "userv"
version = "0.1.0"
edition = "2021"

[dependencies]
colored = "1.9.3"
num_cpus = "1.13"
sysinfo = "0.28"
raw-cpuid = "10.6.0"
serde = "1.0.2"
serde_json = "1.0.1"
libc = "0.2"
